### ISSUE TITLE
Stats are resetting after time period

### ISSUE THREAD

**Issue by rollecode** [digitoimistodude/dude-most-read-posts#2]
Most read posts should count time backwards for example one week or one month. Currently stats are being reset e. g. on every Monday if using the week parameter.

**Comment by timiwahalahti** [comment]
This is valid point and issue. Will probably fix with one custom db table containing post_id, timestamp and read count. With this kind of approach we still avoid same kind overfilling that happens in most other plugins. Count will work as expected and period can be changed anytime easily.

There's just need to make some upgrade process so that old counts will be taken into account in new data structure.

**Comment by timiwahalahti** [comment]
This was implemented in version 2.X.X, please note that there is no upgrade process in place.
